schedules:
- cron: "*/2 * * * *"
  displayName: lancement périodique cyclique
  branches:
    include:
      - main
  always: true

trigger:
- main
- tototest

pool: Default

stages:
- stage: phase_sur_un_agent
  condition: eq(variables['Build.CronSchedule.DisplayName'], 'lancement périodique cyclique')
  jobs:
  - job: execution_script_python
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          print("toto")
          for x in range(10):
            print("tata")
        pythonInterpreter: '/usr/bin/python3'
  - job: dire_script_reussi
    dependsOn: execution_script_python
    condition: succeeded()
    steps:
    - script: echo "job reussi"

- stage: phase_de_deploiement
  dependsOn: []
  condition: not(eq(variables['Build.CronSchedule.DisplayName'], 'lancement périodique cyclique'))
  jobs:
    - deployment: setup_environment
      environment: my_computer.PCP-1147
      strategy: 
        runOnce:
          deploy:
            steps:
            - script: echo "tata pi toto py tutu" > ../../tutoti.txt