trigger:
- main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

variables:
  vmName: 'PCP-1147'

# jobs:
# - deployment: toto
# environment: my_computer.$(vmName)
# strategy: 
#   runOnce:
#     deploy:
steps:
# - script: echo 'toto' > ../../../../toto.txt
# - script: echo "test toto 2"
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print("toto")
      for x in range(10):
        print("tata")
    pythonInterpreter: '/usr/bin/python3'