trigger:
- main
- tototest

pool: Default

stages:
- stage: phase sur un agent
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: execution_script_python
    steps:
    - task: PythonScript@0
      inputs:
        scriptSource: 'inline'
        script: |
          print("toto")
          for x in range(10):
            print("tata")
        pythonInterpreter: '/usr/bin/python3'
  - job: dire_g_fini
    steps:
    - script: echo "j'ai fini"

- stage: phase de déploiement
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/totototest')
  jobs:
    - deployment: setup_environment
      environment: my_computer.$(vmName)
      strategy: 
        runOnce:
          deploy:
            steps:
            - script: echo "tata pi toto py tutu" > ../../tutoti.txt