# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# environment: my_computer.PCP-1147

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

variables:
  # resourceGroup: 'myResourceGroup'
  vmName: 'PCP-1147'

stages:
- stage: stage
  jobs:
  - deployment: NamOfJob
    environment: my_computer.$(vmName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Déploiement sur la machine $(vmName)"
  - deployment: toto
    environment: my_computer.$(vmName)
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: ls
          - script: echo "test toto 2"
  - deployment: tata
    environment: my_computer.$(vmName)
    strategy: 
      runOnce:
        deploy:
          steps:
          - script: echo "test tata 1"
          - script: echo "test tata 2"
  - job: "tata6129"
    displayName: toto
    pool: $(vmName)
    steps:
    - script: echo "step 1 job 2"
    - script: echo "step 2 job 2"